#!/bin/bash
echo  "Atualizando ɪ-🅷🆄🅱, aguarde."
cd  ~
cd izing.io
git checkout master
git pull
cd backend
npm install
rm -rf dist
npm run build
npx sequelize db:migrate
#npx sequelize db:seed
pm2 restart all

echo  "Atualização concluída. Aproveite!"
