name: Deploy Back Docker

on:
  push:
    branches:
      - master
      - release/*
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - master
      - release/*
    paths:
      - 'backend/**'

jobs:
  deploy_back:
    runs-on: ubuntu-22.04
    environment: production
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Use Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: "Verify Node.js version"
        run: node -v

      - name: Build Backend
        run: |
            cd backend
            npm install
            export NODE_OPTIONS="--max_old_space_size=4096"
            CI=false npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for master
        if: github.ref == 'refs/heads/master'
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/ihub-backend:developer-${{ github.sha }} --push ./backend
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/ihub-backend:developer --push ./backend

      - name: Build and push Docker image for release
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/ihub-backend:release-${{ github.sha }} --push ./backend
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/ihub-backend:v${{ github.ref_name }} --push ./backend
          docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/ihub-backend:latest --push ./backend
